import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Providers } from "~/components/providers";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html className='bg-zinc-800 text-zinc-100' lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Providers>
          <div className="font-sans grid grid-rows-[1fr_auto] min-h-screen">
            <main className="w-[min(calc(100%-2rem),56rem)] mx-auto">
              {children}
            </main>
            <footer className="text-center text-sm">Made with love by 💙 <a href="https://github.com/BrunosPanizzi" target="_blank" rel="noopener noreferrer" className="text-cyan-100 hover:text-cyan-200 hover:underline">Bruno Panizzi</a></footer>
          </div>
        </Providers>
      </body>
    </html>
  );
}
